api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiPlatform/Entity'
    formats:
        jsonapi: ['application/vnd.api+json']
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    patch_formats:
        jsonapi: ['application/vnd.api+json']
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
