doctrine:
    dbal:
        host: '%env(DB_HOST)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        dbname: '%env(DB_DATABASE)%'
        port: '%env(DB_PORT)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
